name: Crawler runner

on:
  schedule:
    - cron: '0 * * * *'  # Запуск каждый час в 00 минут (UTC)
  workflow_dispatch:       # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          ref: main  # ветку: main или master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crawler
        run: python NeedFree.py

      - name: Update free details json
        run: |
          git pull
          git config --global user.name 'BALCETUL'
          git config --global user.email 'youremail@example.com'
          git commit -am "Автоматическое обновление free_goods_detail.json"
          git push
